name: 'Create Release'
description: 'Create a release with a tag'

inputs:
  version:
    description: 'The version number for the git tag'
    required: true
  artifacts:
    description: 'The path to the artifact to upload'
    required: true


runs:
  using: "composite"
  steps:
    # add a step that zips the path specified in the artifacts input
    - name: Zip artifact
      shell: bash
      run: |
        zip -r release-artifact.zip ${{ inputs.artifacts }}
    - name: Create git tag
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git tag v${{ inputs.version }}
        git push origin v${{ inputs.version }}
        # create a release with the tag
        gh release create v${{ inputs.version }} --title "Release v${{ inputs.version }}" --notes "Release v${{ inputs.version }}" --attach release-artifact.zip
      