name: Deploy Release to Environment

description: |
  This action downloads a release asset from a GitHub release and deploys it to the specified environment.

inputs:
  release:
    description: 'GitHub Release'
    required: true
    default: 'latest'
  asset-name:
    description: 'Asset Name'
    required: true
    default: 'release-artifact.zip'
  github-token:
    description: 'Github Token'
    required: true
  target:
    description: 'Target Environment'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Download Release Asset
      uses: kkhelif/maven-reusable-workflows-actions/actions/download-release-asset@main
      with:
        release: ${{ inputs.release }}
        asset-name: ${{ inputs.asset-name }}
        github-token: ${{ inputs.github-token }}

    - name: Deploy Asset
      run: | 
          echo "Deploying ${{ inputs.asset-name }} to ${{ inputs.target }}"
          tree 
      shell: bash
