name: CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      version:
        required: true
        type: string
      cake-script:
        required: false
        type: string
    secrets:
      token:
        required: true
   
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Build Number
      run: echo "BUILD_NUMBER=${{ inputs.version }}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.token }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      if: inputs.cake-script == ''
      run: | 
        mvn versions:set -DnewVersion=${{ inputs.version }}
        mvn -B package --file pom.xml
        mvn test
      working-directory: ${{ inputs.working-directory }}

    - name: Build and Test using cake script
      if: inputs.cake-script != '' 
      uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b
      with:
        script-path: ${{ inputs.cake-script }}
        target: ./my-app/target/
        arguments: |
          file-version: ${{ inputs.version }}
      
    - name: Debug
      run: tree -a

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@ca89ad036b5fcd524c1017287fb01b5139908408
      if: always()
      with:
        files: |
          ${{ inputs.working-directory }}/target/surefire-reports/**/*.xml

    - name: Use Create Git Tag Action
      if: github.ref == 'refs/heads/main'
      uses: kkhelif/maven-reusable-workflows-actions/actions/create-release@main
      with:
        version: '${{ inputs.version }}'
        artifacts: '${{ inputs.working-directory }}/target/*.jar'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: ${{ inputs.working-directory }}/target/*${{ inputs.version }}.jar

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Super-Linter (dry-run)
        run: echo "Run Super-Linter (dry-run)"
      # - name: Run Super-Linter
      #   uses: super-linter/super-linter@v5
      #   env:
      #     VALIDATE_ALL_CODEBASE: true
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
