name: CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true
        
permissions:
  contents: write
  
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.token }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: | 
        mvn versions:set -DnewVersion=${{ inputs.version }}
        mvn -B package --file pom.xml
      working-directory: ${{ inputs.working-directory }}

    - name: Use Create Git Tag Action
      if: github.ref == 'refs/heads/main'
      uses: SolidifyDemo/maven-reusable-workflows-actions/actions/create-release@main
      with:
        version: '${{ inputs.version }}'
        artifacts: 'target/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
