name: Deploy to Environment

on:
  workflow_call:
    inputs:
      release:
        description: 'GitHub Release'
        required: true
        default: 'latest'
        type: string
      environment:
        description: 'GitHub Release'
        required: true
        default: 'latest'
        type: string

jobs:
  deploy-prod:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Download release asset
        uses: SolidifyDemo/maven-reusable-workflows-actions/actions/download-release-asset@main
        with:
          release: ${{ github.event.inputs.release }}
          asset-name: 'release-artifact.zip'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: debug
        run: tree

      - name: Deploy asset
        run: echo 'Deploying artifact'
        shell: bash